# CLI command to create env using this file:
# conda env create -f conda.yaml

name: openhtf
channels:
  - defaults
  - conda-forge # for the newest pip
dependencies:
  - python=3.9
  - pip>=22
  - pip:
      - openhtf
      - six
